apiVersion: batch/v1
kind: Job
metadata:
  name: gkejobfromgithub
  namespace: default
spec:
  template:
    metadata:
      name: gkejob
    spec:
      containers:
        - name: hello
          image: busybox
          command:
            - "sh"
            - "-c"
            - "echo Hello, Google Team!"
      restartPolicy: Never
  backoffLimit: 4
