apiVersion: batch/v1
kind: Job
metadata:
  name: gkejobfromgithub
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(200) =~ s/(.{100})/$1\\n/gr"]
      - name: hello
        image: busybox
        command: ["sh", "-c", "echo Hello, Google!"]
      restartPolicy: Never
  backoffLimit: 4
